In [1]:
import numpy as np

In [2]:
np.fromfunction?

In [3]:
nums = np.arange(100).reshape(20, 5)
print(nums)
nums.mean(axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


array([47.5, 48.5, 49.5, 50.5, 51.5])

In [4]:
b = np.arange(1, 10, 2)
b.mean()

5.0

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr.sum(axis=0)

array([5, 7, 9])

# Boolean Arrays
This is a test on boolean arrays.

In [6]:
nums = np.arange(100).reshape(20, -1)

In [7]:
nums[:, nums.sum(axis=0) % 3 == 1]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19],
       [21, 24],
       [26, 29],
       [31, 34],
       [36, 39],
       [41, 44],
       [46, 49],
       [51, 54],
       [56, 59],
       [61, 64],
       [66, 69],
       [71, 74],
       [76, 79],
       [81, 84],
       [86, 89],
       [91, 94],
       [96, 99]])

In [8]:
#Stacking arrays side by side
arra = nums[:, nums.sum(axis=0) % 3 == 1] #Sum misses 3 by 1
arrb = nums[:, nums.sum(axis=0) % 3 == 0] #Sum is divisible by 3
arrc = np.hstack((arra, arrb))
arrc

array([[ 1,  4,  2],
       [ 6,  9,  7],
       [11, 14, 12],
       [16, 19, 17],
       [21, 24, 22],
       [26, 29, 27],
       [31, 34, 32],
       [36, 39, 37],
       [41, 44, 42],
       [46, 49, 47],
       [51, 54, 52],
       [56, 59, 57],
       [61, 64, 62],
       [66, 69, 67],
       [71, 74, 72],
       [76, 79, 77],
       [81, 84, 82],
       [86, 89, 87],
       [91, 94, 92],
       [96, 99, 97]])

In [9]:
import sklearn.datasets
iris = sklearn.datasets.load_iris().data
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
iris.shape

(150, 4)

In [11]:
iris.ndim

2

In [12]:
iris.mean(axis = 0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [13]:
iris[iris.mean(axis=1) > 2.5]

array([[5.1, 3.5, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3

In [14]:
iris[:, 2] #slicing a whole column

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [15]:
#Z-score of the data z = (x – μ) / σ
iris_z = (iris - iris.mean()) / iris.std()
iris_z

array([[ 0.82858665,  0.01798522, -1.04592915, -1.65388022],
       [ 0.72726147, -0.23532773, -1.04592915, -1.65388022],
       [ 0.62593629, -0.13400255, -1.09659174, -1.65388022],
       [ 0.5752737 , -0.18466514, -0.99526657, -1.65388022],
       [ 0.77792406,  0.06864781, -1.04592915, -1.65388022],
       [ 0.98057441,  0.22063558, -0.89394139, -1.55255505],
       [ 0.5752737 , -0.03267737, -1.04592915, -1.60321764],
       [ 0.77792406, -0.03267737, -0.99526657, -1.65388022],
       [ 0.47394852, -0.28599032, -1.04592915, -1.65388022],
       [ 0.72726147, -0.18466514, -0.99526657, -1.70454281],
       [ 0.98057441,  0.1193104 , -0.99526657, -1.65388022],
       [ 0.67659888, -0.03267737, -0.94460398, -1.65388022],
       [ 0.67659888, -0.23532773, -1.04592915, -1.70454281],
       [ 0.42328593, -0.23532773, -1.19791692, -1.70454281],
       [ 1.18322477,  0.27129817, -1.14725433, -1.65388022],
       [ 1.13256218,  0.47394852, -0.99526657, -1.55255505],
       [ 0.98057441,  0.

In [16]:
iris_z.mean()

1.1842378929335003e-16

In [17]:
iris_z.std()

1.0

# Numpy Exercises

Finding the combination of two arrays using meshgrid. numpy.meshgrid is used to 'create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing.'

In [18]:
arr1 = np.array([1, 2, 6])
arr2 = np.array([4, 6, 4])
arrn = np.array(np.meshgrid(arr1, arr2)).T.reshape(-1, 2) #meshgrid returns a list; Using -1 in reshape ensures that the 
#other dimension is automatically calculated
print(arrn)

[[1 4]
 [1 6]
 [1 4]
 [2 4]
 [2 6]
 [2 4]
 [6 4]
 [6 6]
 [6 4]]


Find common values between two numpy arrays using numpy.intersect1d

In [19]:
rng = np.random.Generator(np.random.MT19937())
arr1 = rng.integers(100, 100000, 10000)
arr2 = rng.integers(100, 100000, 10000)

#Find the average intersections of the above arrays after 1000 tries
count = 0
for _ in range(1000):
    count += len(np.intersect1d(arr1, arr2))
    
print(count/1000)

904.0


# More Numpy Exercises

###  1. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [20]:
#One solution
arr1 = rng.integers(0, 10, 100)
for index, elem in np.ndenumerate(arr1):
    if elem < 9 and elem > 2:
        arr1[index] *= -1
        
arr1

array([-4, -8,  0, -8, -5,  0, -5, -8, -6,  1,  0,  1, -4, -8, -3, -5, -3,
       -5,  0, -5,  1,  2, -4, -4,  9,  0, -7, -7,  2, -8, -7, -5, -5,  9,
       -8,  9, -7, -4, -5, -7,  2, -6, -7, -5, -3, -3, -6, -6, -6, -3, -4,
       -7,  2, -4, -4, -5, -8, -3, -3,  1, -5, -6, -8,  2,  9, -3, -7, -6,
        0, -3,  0,  9, -6, -8,  2, -5,  0,  2, -3,  2, -5, -7, -6, -5,  9,
        1, -5, -3,  1, -5,  0, -6, -5,  9,  2,  9, -5, -7,  1, -5],
      dtype=int64)

In [21]:
#Correctly
arr2 = rng.integers(0, 10, 100)
arr2[(3 < arr2) & (8 > arr2)] *= -1
arr2

array([-6, -6, -4,  3, -5, -5, -7,  0, -5,  2,  2,  2,  9, -6,  0,  2,  9,
        3,  0,  3, -7,  1, -7,  8, -4,  1,  0, -6, -7,  1, -4, -6,  8,  3,
        1, -6, -7,  1, -7,  0, -6,  0, -7, -6,  0, -5,  9,  2,  9,  1, -6,
        8, -7,  9, -6, -7, -7,  3,  8,  8, -5,  8,  9, -7, -6, -7, -5,  9,
        8, -7, -4, -7,  1, -6,  9,  8, -6,  3,  8,  0,  9,  9,  1, -7, -6,
        1, -6, -6,  8, -5,  1,  3,  9, -6,  2,  8,  1, -4,  1,  1],
      dtype=int64)

### 2. Given a two dimensional array, how to extract unique rows?



In [22]:
#Getting unique rows
#initial soln
#Two arrays are similar if they have the same elements in the same order

arr1 = rng.integers(0, 10, 100).reshape(-1, 5)

#arr1 == arr1[x] provides a boolean array
#Sampling all across the horizontal axis summarizes to true iff all are true
#Use nonzero() to only give the true values
#If the size of the resultant array is >1 it repeats
#Hence:

for row in arr1:
    x = (arr1 == row).all(axis=1).nonzero()
    #x is a tuple with an ndarray, x[0], showing position row
    #x[0] is what we want
    
    if len(x[0]) == 1: #does not repeat
        print(row)

[0 4 8 5 8]
[7 7 5 8 6]
[7 1 2 7 4]
[0 0 3 4 4]
[1 0 1 4 6]
[5 1 1 6 3]
[9 0 8 8 8]
[3 1 8 6 0]
[7 7 5 3 2]
[6 6 0 7 8]
[5 9 1 4 9]
[3 9 2 3 4]
[5 0 8 5 9]
[6 6 3 9 5]
[2 4 1 6 7]
[7 1 6 3 8]
[8 0 4 3 3]
[7 9 5 9 7]
[8 9 9 2 3]
[3 9 2 6 6]


In [23]:
#Given solution
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


In [24]:
#Testing both solutions:
#My soln
def find_unique1(arr1):
    for row in arr1:
        x = (arr1 == row).all(axis=1).nonzero()
        if len(x[0]) == 1: #does not repeat
            print(row)
 
#Other proposed soln
def find_unique2(Z):
    uZ = np.unique(Z, axis=0)
    print(uZ)
    
arrx = np.random.randint(0, 2, (10,3))
print(arrx)
print()
print('-----find unique 1------')
find_unique1(arrx)
print()
print('-----find unique 2------')
find_unique2(arrx)

#The two functions act differently:
#find_unique1 returns non-repeating(unique) rows only
#find_unique2 returns all rows, with each row --repeating or non-repeating--
#appearing once, essentially removes repetition.

[[1 0 0]
 [0 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 1 0]
 [0 1 0]
 [1 1 0]
 [0 0 0]
 [0 1 1]]

-----find unique 1------
[1 0 0]

-----find unique 2------
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


### 3. How to get the n largest values of an array

In [25]:
#Get the n largest values
#Going to sort array
'sort' in dir(np)

True

In [26]:
np.sort??

In [27]:
#Use the iris dataset created from sklearn
iris_sorted = np.sort(iris.flat)
iris_sorted.shape

(600,)

In [28]:
#given any n, return a list of size n of the 
#n-largest elements in that array
iris_sorted[590:]

#Suppose n = 10, the largest 10 digits in the iris dataset

array([7.2, 7.2, 7.3, 7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [29]:
#Hence,the final solution is:
n = 5 #the largest set we want
arr = np.arange(10000000)
np.random.shuffle(arr)
print( '----mysoln----')
print((np.sort(arr))[arr.size - n:])

#proposed soln
#slow
print( '----proposed slow----')
print(arr[np.argsort(arr)[-n:]])

#Fast
print( '----proposed fast----')
print(arr[np.argpartition(-arr, n)[:n]])

#Slow and mysoln are comparatively slow
#Fast is quite fast
#Sort returns a sorted copy whereas argsort() returns the indices of the elements
#if the array were sorted

#The fast algorithm uses partationing, partitoning the array based on index
#np.partition(ndarray, index) returns an array in which the index given will have
#its proper element (i.e -- after partitioning the element at arr[index] is the same as after sorting)
#To the left of index, are elements less than... to the right elements greater than index... although
#not guaranteed to be in their right positions!

----mysoln----
[9999995 9999996 9999997 9999998 9999999]
----proposed slow----
[9999995 9999996 9999997 9999998 9999999]
----proposed fast----
[9999998 9999997 9999999 9999996 9999995]


### How to find the most frequent value in an array?

In [30]:
#How I'd do it
arr1 = rng.integers(0, 1000000, 100000000)

In [31]:
elem, counts = np.unique(arr1, return_counts = True)
print(elem[np.argsort(counts)[::-1][0]], ' --> ', np.sort(counts)[::-1][0])

922127  -->  150


In [32]:
#The solution given
print(np.bincount(arr1).argmax(), ' --> ', np.bincount(arr1).max())

#According to the docs -->
#bincount 'Count number of occurrences of each value in array of non-negative ints.'
#Also, the size of the bin, is 1 larger than the largest element in the given array
#e.g. if given an array of 5 unique elements {1, 3, 5, 21, 1001}, the size of the 
#resultant array is 1002

#Argmax 'Returns the indices of the maximum values along an axis.'

#This is faster, NOW WE KNOW!

513044  -->  150


### Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

In [85]:
#My soln
#np.bincount(A) returns an array of size(A.max())
#each bin in Bin is no. of times Bin[index] has occured

#Create array C that is a bincount, min=0, max=1499

C = rng.integers(0, 1499, 1500)

In [86]:
#C[n] for any 0 <= n < 1500 means that n appears C[n] times in C
#To build A, put as many n in A as C[n]
#size of A is sum of C
C.sort()
A = np.zeros(C.sum(), dtype = int)
pos_ina = 0
for n in range(len(C)):
    #At every n, make C[n] n's in A
    
    for _ in range(C[n]):
        A[pos_ina] = n
        pos_ina += 1
        
(np.bincount(A) == C).all()

True

In [92]:
#The proposed soln
#uses np.repeat
A_beta = np.repeat(np.arange(len(C)), C)
(np.bincount(A_beta) == C).all()

#Overly less cumbersome

True